fix #1490: launch template version fetching (#1495)
### Summary
> Describe your changes.

fixes an issue in `describe_launch_template_versions` where fetching
versions required specifying `$Latest` or `$Default`. instead of
restricting to only those versions of a template, this reverts changes
from PR #1486 , restoring the ability to fetch all versions of a launch
template.


### Related issues or links
> Include links to relevant issues or other pages.

- https://github.com/cartography-cncf/cartography/issues/1490


### Checklist

Provide proof that this works (this makes reviews move faster). Please
perform one or more of the following:
- [ ] Update/add unit or integration tests.
- [x] Include a screenshot showing what the graph looked like before and
after your changes.
- [x] Include console log trace showing what happened before and after
your changes.

Before: 
```
botocore.exceptions.ClientError: An error occurred (MissingParameter) when calling the DescribeLaunchTemplateVersions operation: To describe the launch template data for all your launch templates, for '--versions' specify '$Latest', '$Default', or both, and omit '--launch-template-id', '--launch-template-name', and version numbers. To describe the launch template data for a specific launch template, specify '--launch-template-id' or '--launch-template-name', and for '--versions' specify one or more of the following values: '$Latest', '$Default', or one or more version numbers.
```

After:

```
INFO:cartography.intel.aws.ec2.launch_templates:Syncing launch templates for region 'us-west-2' in account 'XXX'.
INFO:cartography.intel.aws.ec2.launch_templates:Running launch template cleanup job.
INFO:cartography.graph.statement:Completed LaunchTemplate statement #1
INFO:cartography.graph.statement:Completed LaunchTemplate statement #2
INFO:cartography.graph.job:Finished job LaunchTemplate
```

<img width="667" alt="Screenshot 2025-03-26 at 4 21 33 PM"
src="https://github.com/user-attachments/assets/39cd72d6-fe2b-4d90-b90b-288bdbbfd6ef"
/>



If you are changing a node or relationship:
- [ ] Update the
[schema](https://github.com/lyft/cartography/tree/master/docs/root/modules)
and
[readme](https://github.com/lyft/cartography/blob/master/docs/schema/README.md).

If you are implementing a new intel module:
- [ ] Use the NodeSchema [data
model](https://cartography-cncf.github.io/cartography/dev/writing-intel-modules.html#defining-a-node).

---------

Signed-off-by: Ishaan Verma <iverma@foursquare.com>