Sync inspector findings sequentially (#1672)
### Summary
Follow up from 
After a few tests locally and in a running environment, moving the sync
of inspector findings one account at a time.
This reduces the performance gain from syncing multiple account async,
but avoids concurrency problems with the Neo4J Session used that is not
concurrent safe.
For future reference, the error came during the `ensure_indexes`
transaction that performs an autocommit and cannot live within other
transactions, hence the `neo4j_session.run(query)` command.
```
File "/code/venvs/venv/lib/python3.10/site-packages/cartography/intel/aws/inspector.py", line 235, in load_inspector_findings
    load(
  File "/code/venvs/venv/lib/python3.10/site-packages/cartography/client/core/tx.py", line 276, in load
    ensure_indexes(neo4j_session, node_schema)
  File "/code/venvs/venv/lib/python3.10/site-packages/cartography/client/core/tx.py", line 255, in ensure_indexes
    neo4j_session.run(query)
  File "/code/venvs/venv/lib/python3.10/site-packages/neo4j/work/simple.py", line 217, in run
    self._autoResult._run(
  File "/code/venvs/venv/lib/python3.10/site-packages/neo4j/work/result.py", line 115, in _run
    self._attach()
  File "/code/venvs/venv/lib/python3.10/site-packages/neo4j/work/result.py", line 204, in _attach
    self._connection.fetch_message()
  File "/code/venvs/venv/lib/python3.10/site-packages/neo4j/io/_common.py", line 187, in inner
    func(*args, **kwargs)
  File "/code/venvs/venv/lib/python3.10/site-packages/neo4j/io/_bolt4.py", line 291, in fetch_message
    details, summary_signature, summary_metadata = next(self.inbox)
  File "/code/venvs/venv/lib/python3.10/site-packages/neo4j/io/_common.py", line 83, in __next__
    tag, fields = self.pop()
  File "/code/venvs/venv/lib/python3.10/site-packages/neo4j/io/_common.py", line 77, in pop
    return next(self._messages)
ValueError: generator already executing
```

### Related issues or links
- https://github.com/cartography-cncf/cartography/pull/1654
-
https://github.com/neo4j/neo4j-python-driver/blob/52485565520fb7ba0babc9fc317e0fa91a1f173e/neo4j/work/simple.py#L56-L58
-
https://github.com/cartography-cncf/cartography/blob/747d8879fd7b8fb473ca33b6b306ffb472b64246/cartography/client/core/tx.py#L255
- https://cloud-native.slack.com/archives/C080M2LRLDA/p1751406934628539


### Checklist

Provide proof that this works (this makes reviews move faster). Please
perform one or more of the following:
- [ ] Update/add unit or integration tests.
- [ ] Include a screenshot showing what the graph looked like before and
after your changes.
- [x] Include console log trace showing what happened before and after
your changes.

If you are changing a node or relationship:
- [ ] Update the
[schema](https://github.com/cartography-cncf/cartography/tree/master/docs/root/modules)
and
[readme](https://github.com/cartography-cncf/cartography/blob/master/docs/schema/README.md).

If you are implementing a new intel module:
- [ ] Use the NodeSchema [data
model](https://cartography-cncf.github.io/cartography/dev/writing-intel-modules.html#defining-a-node).

Signed-off-by: Eryx Paredes <eryxp@lyft.com>